import LocalizedStrings from "react-native-localization";
export default localization = new LocalizedStrings({
    en: {
        home: 'Home',
        menu: 'Menu',
        search: 'Search',
        cart: 'cart',
        settings: 'Settings',
        add:'add',
        SearchPlaceHolder:'what are you searching for',
        merchentName:'Baalat Elzad',
        freeDlievery:'free delivery',
        homeDrawer:'Home',
        profileDrawer:'Profile',
        cartDrawer:'My Cart',
        call_usDrawer:'Call us',
        conditionsDrawer:'Conditions',
        exitDrawer:'Exit',
        search:'search',
        cartProductName:'Name',
        cartProductWeight:'Weight',
        cartProductQuantity:'Quantity',
        cartProductPrice:'Price',
        MyOrders:'My Orders',
        signup:'Register',
        RegisterClient:'Register Client',
        registerUsername:'Client name',
        registerPhone:'phone',
        registerPassword:'password',
        registerReEnterPassword:'re-enter password',
        Signin:'Sign in',
        login:'login',
        arabic:'Arabic',
        english:'English',
        restartApp:'please restart the app to set the new configurations.',
    },
    ar: {
        home: 'الرئيسية',
        menu: 'القائمة',
        search: 'البحث',
        cart: 'العربة',
        settings: 'الإعدادات',
        add:'أضف',
        SearchPlaceHolder:'ما الذي تبحث عنه',
        merchentName:'بقالة الزاد',
        freeDlievery:'توصيل مجاني',
        homeDrawer:'الصفحه الرئيسية',
        profileDrawer:'الصفحة الشخصية',
        cartDrawer:'مشترياتي',
        call_usDrawer:'إتصل بنا',
        conditionsDrawer:'الشروط والأحكام',
        exitDrawer:'خروج',
        search:'بحث',
        cartProductName:'الإسم',
        cartProductWeight:'الوزن',
        cartProductQuantity:'الكمية',
        cartProductPrice:'السعر',
        MyOrders:'طلباتي',
        signup:'تسجيل',
        RegisterClient:'تسجيل عميل',
        registerUsername:'اسم العميل',
        registerPhone:'رقم الجوال',
        registerPassword:'كلمة المرور',
        registerReEnterPassword:'إعادة كلمة المرور',
        Signin:'تسجيل الدخول',
        login:'دخول',
        arabic:'عربي',
        english:'إنجليزي',
        restartApp:'من فضلك اعد تحميل التطبيق لتفعيل التغيرات الجديدة.',
    }
})
